### ISSUE TITLE
Missing closing li tag @ line 56; 'SERVICE' and 'WORK' appear to be duplicated, not sure what the intention are

### ISSUE THREAD

**Issue by vegetasrevenge** [tyreik-brett/codeup-design-project#1]
https://github.com/tyreik-brett/codeup-design-project/blob/e3930da1fc3bba5430401bff5e744ffd67c521a2/design-project-bootstrap.html#L50-L76

**Comment by TWilliams2022** [comment]
I'm trying to center the image but not sure if I should remove it from the li (line 57-62)

**Comment by TWilliams2022** [comment]
& all 3 navbars are being shown in VS screen unfortunately
